[project]
name = "deploy-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
     "fastapi[standard]>=0.113.0,<0.114.0",
     "pydantic>=2.7.0,<3.0.0",
]
