apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sample
  namespace: deploy-sample
  labels:
    app: deploy-sample
    sidecar.istio.io/inject: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-sample
  template:
    metadata:
      labels:
        app: deploy-sample
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: sample-deploy-container
        image: docker.io/library/deploy-sample:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20