environments:
  # we will use the default environment as our sandbox
  default:
    values:
      - key: value # example of a value that can be overridden in default environment
  dev:
  stage:
  prod:
    values:
      - key: value # example of a value that can be overridden in <name> environment
---
repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: kiali
    url: https://kiali.org/helm-charts

---
releases:
  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
    version: 1.26
    values:
    - defaultRevision: default
  - name: istiod
    namespace: istio-system
    createNamespace: true
    chart: istio/istiod
    version: 1.26
    installed: true # Ensure this is true to actually install the chart
    needs:
    - istio-system/istio-base
  - name: deploy-sample # name of the release
    chart: ./deploy-sample # path to the chart
    namespace: deploy-sample # target namespace
    createNamespace: true # create namespace if it does not exist
    installed: true
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/prometheus
    values:
      - prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
  - name: grafana
    namespace: monitoring
    version: 9.2.10
    createNamespace: true
    chart: grafana/grafana
    values:
      - persistence:
          enabled: true
          size: 10Gi
      - adminPassword: "admin" # Set your Grafana admin password here
  - name: kiali
    namespace: monitoring
    chart: kiali/kiali-server